apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: tranductung0701/spring-petclinic-config-server:latest
        ports:
        - containerPort: 8888
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  selector:
    app: config-server
  ports:
  - port: 8888
    targetPort: 8888
    #nodePort: 30888
  type: NodePort
