apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
      - name: genai-service
        image: tranductung0701/spring-petclinic-genai-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 30084
  selector:
    app: genai-service
