   apiVersion: networking.k8s.io/v1
   kind: Ingress
   metadata:
     name: petclinic-ingress
     namespace: petclinic-dev
     annotations:
       nginx.ingress.kubernetes.io/rewrite-target: /$1
   spec:
     rules:
     - host: petclinic.local
       http:
         paths:
         - path: /customers(/|$)(.*)
           pathType: Prefix
           backend:
             service:
               name: customers-service
               port:
                 number: 8080
         - path: /genai(/|$)(.*)
           pathType: Prefix
           backend:
             service:
               name: genai-service
               port:
                 number: 8081
         - path: /vets(/|$)(.*)
           pathType: Prefix
           backend:
             service:
               name: vets-service
               port:
                 number: 8082
         - path: /visits(/|$)(.*)
           pathType: Prefix
           backend:
             service:
               name: visits-service
               port:
                 number: 8083